"""Self-contained browser page for in-calibration vertical-post leveling."""

PAGE = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Level the rink from vertical posts</title>
<style>
:root{color-scheme:dark;font-family:system-ui,sans-serif;--bg:#07151e;--panel:#102734;--line:#59d7ff;--muted:#a9c5d3;--ok:#75efad;--bad:#ff8c95}
*{box-sizing:border-box}body{margin:0;background:linear-gradient(160deg,#07151e,#113347);color:#eefaff}.page{max-width:1500px;margin:auto;padding:22px}
h1{margin:.2rem 0}.lead{color:var(--muted);max-width:1000px}.layout{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:18px}
.panel{background:rgba(16,39,52,.94);border:1px solid #315266;border-radius:16px;padding:14px;box-shadow:0 16px 45px #0007}
.tabs,.actions,.angles,.finish{display:flex;gap:8px;flex-wrap:wrap}.tabs{margin-bottom:10px}button,input{font:inherit;border-radius:9px;border:1px solid #527184;background:#16394b;color:#fff;padding:9px 12px}
button{cursor:pointer}button.active,button.primary{background:#176f91;border-color:#64dfff}button:disabled{opacity:.45;cursor:not-allowed}
.stage{height:min(70vh,820px);min-height:420px;background:#02080c;border-radius:10px;overflow:hidden;position:relative;touch-action:none}.stage canvas{width:100%;height:100%;display:block}
#preview{width:100%;height:100%;object-fit:contain;display:none}.actions{margin-top:10px}.angles label{display:grid;gap:4px;color:var(--muted);flex:1}.angles input{width:100%}
#status{min-height:76px;padding:11px;margin:12px 0;background:#0a1d27;border-radius:9px;color:var(--muted)}#status.ok{color:var(--ok)}#status.bad{color:var(--bad)}
.tips{color:var(--muted);font-size:.92rem;padding-left:20px}.finish{margin-top:14px}.finish button{flex:1}button.destructive{border-color:#d96a73;color:#ffd8dc}.busy:after{content:"Working…";position:absolute;inset:0;display:grid;place-items:center;background:#001018bb;font-size:1.4rem}
@media(max-width:900px){.layout{grid-template-columns:1fr}.stage{height:58vh}}
</style></head><body><main class="page"><h1>Level the rink from vertical posts</h1>
<p class="lead">Mark the top and bottom of at least three tall upright wall or glass posts, spread across both cameras. Each pair of clicks is one post. The pitch and roll estimate updates automatically after each completed selection or adjustment.</p>
<div class="layout"><section class="panel"><div class="tabs"><button data-tab="0" class="active">Left camera</button><button data-tab="1">Right camera</button><button data-tab="preview" id="previewTab" disabled>Preview</button></div>
<div class="stage" id="stage"><canvas id="canvas"></canvas><img id="preview" alt="Leveled panorama preview"></div>
<div class="actions" id="pointActions"><button id="undo">Undo point</button><button id="clear">Clear camera</button><button id="fit">Fit image</button></div></section>
<aside class="panel"><div class="angles"><label>Pitch <input id="pitch" type="number" min="-180" max="180" step="0.25"></label><label>Roll <input id="roll" type="number" min="-180" max="180" step="0.25"></label></div>
<div id="status" role="status">Choose a camera and mark post endpoint pairs. Scroll to zoom, Shift-drag or middle-drag empty space to pan, and drag a numbered endpoint to adjust it.</div>
<button id="previewButton" class="primary">Preview angles</button>
<ul class="tips"><li>Avoid rink corners, sloping beams, and short marks.</li><li>Use posts across the full view; clustered marks cannot determine tilt.</li><li>Preview performs one small NONA still render. Final maps and the Enblend seam are generated only after this dialog.</li></ul>
<div class="finish"><button id="skip">Skip leveling</button><button id="cancel" class="destructive">Cancel calibration</button><button id="use" class="primary" disabled>Use angles</button></div></aside></div></main>
<script>const S=__STATE__,auth=location.hash.slice(1),canvas=document.querySelector('#canvas'),ctx=canvas.getContext('2d'),stage=document.querySelector('#stage'),preview=document.querySelector('#preview');
const images=[new Image(),new Image()],points=[[],[]],views=[{},{}];let camera=0,mode='camera',drag=null,busy=false,finishing=false,estimateTimer=null,estimateSerial=0,previewRotation=null,previewUrl=null;
const pitch=document.querySelector('#pitch'),roll=document.querySelector('#roll'),status=document.querySelector('#status'),use=document.querySelector('#use'),previewButton=document.querySelector('#previewButton');pitch.value=S.rotation[1];roll.value=S.rotation[2];
function setStatus(text,kind=''){status.textContent=text;status.className=kind}function rotation(){return [S.rotation[0],Number(pitch.value),Number(roll.value)]}function invalidatePreview(){previewRotation=null;use.disabled=true;document.querySelector('#previewTab').disabled=true}
async function request(url,data){const options={headers:{'X-Editor-Token':auth}};if(data!==undefined){options.method='POST';options.headers['Content-Type']='application/json';options.body=JSON.stringify(data)}const response=await fetch(url,options);if(!response.ok){let error='Request failed';try{error=(await response.json()).error||error}catch(_){}throw new Error(error)}return response}
async function post(url,data){return (await request(url,data)).json()}async function image(url){const blob=await (await request(url)).blob(),objectUrl=URL.createObjectURL(blob),result=new Image();try{await new Promise((resolve,reject)=>{result.onload=resolve;result.onerror=()=>reject(Error('Unable to load selector image'));result.src=objectUrl})}catch(error){URL.revokeObjectURL(objectUrl);throw error}result.objectUrl=objectUrl;return result}function releaseObjectUrls(){images.forEach(value=>{if(value.objectUrl){URL.revokeObjectURL(value.objectUrl);value.objectUrl=null}});if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null}}
function resize(){const d=devicePixelRatio||1,w=Math.max(1,stage.clientWidth),h=Math.max(1,stage.clientHeight);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);draw()}
function fit(){const img=images[camera],w=stage.clientWidth,h=stage.clientHeight;if(!img.naturalWidth)return;const scale=Math.min(w/img.naturalWidth,h/img.naturalHeight);views[camera]={scale,x:(w-img.naturalWidth*scale)/2,y:(h-img.naturalHeight*scale)/2};draw()}
function view(){return views[camera]}function sourcePoint(e){const r=canvas.getBoundingClientRect(),v=view();return [(e.clientX-r.left-v.x)/v.scale,(e.clientY-r.top-v.y)/v.scale]}function screenPoint(p){const v=view();return [v.x+p[0]*v.scale,v.y+p[1]*v.scale]}
function draw(){if(mode!=='camera')return;const img=images[camera],v=view();ctx.clearRect(0,0,stage.clientWidth,stage.clientHeight);if(!img.naturalWidth||!v.scale)return;ctx.drawImage(img,v.x,v.y,img.naturalWidth*v.scale,img.naturalHeight*v.scale);ctx.lineWidth=3;ctx.strokeStyle='#59d7ff';ctx.fillStyle='#ff5968';ctx.font='bold 13px system-ui';for(let i=0;i<points[camera].length;i+=2){if(i+1<points[camera].length){const a=screenPoint(points[camera][i]),b=screenPoint(points[camera][i+1]);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}}points[camera].forEach((p,i)=>{const q=screenPoint(p);ctx.beginPath();ctx.arc(q[0],q[1],7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.fillText(String(Math.floor(i/2)+1)+(i%2?'B':'A'),q[0]+10,q[1]-8);ctx.fillStyle='#ff5968'})}
function allPosts(){const result=[];for(let c=0;c<2;c++)for(let i=0;i+1<points[c].length;i+=2)result.push({image_index:c,first:points[c][i],second:points[c][i+1]});return result}
function saveDraft(){try{localStorage.setItem(S.draftKey,JSON.stringify(points))}catch(error){console.warn('Could not save selector draft',error)}}function scheduleEstimate(){const serial=++estimateSerial;invalidatePreview();saveDraft();clearTimeout(estimateTimer);previewButton.disabled=false;const posts=allPosts(),total=posts.length;if(points.some(p=>p.length%2)||posts.every(p=>p.image_index!==0)||posts.every(p=>p.image_index!==1)||total<3){setStatus(`${total} complete post${total===1?'':'s'} selected. Use at least three complete pairs, including both cameras.`);return}previewButton.disabled=true;setStatus('Estimating pitch and roll from the calibrated viewing rays…');estimateTimer=setTimeout(()=>{if(drag){scheduleEstimate();return}post('/api/estimate',{posts:allPosts(),rotation:rotation()}).then(j=>{if(serial!==estimateSerial)return;pitch.value=j.rotation_degrees[1].toFixed(3);roll.value=j.rotation_degrees[2].toFixed(3);previewButton.disabled=false;setStatus(`Used ${j.inlier_indices.length} of ${j.residual_degrees.length} posts; RMS angular residual ${j.rms_residual_degrees.toFixed(2)}°. Preview the result, then fine-tune if needed.`,'ok')}).catch(e=>{if(serial===estimateSerial){previewButton.disabled=false;setStatus(e.message,'bad')}})},150)}
canvas.addEventListener('pointerdown',e=>{if(busy||mode!=='camera')return;canvas.setPointerCapture(e.pointerId);const r=canvas.getBoundingClientRect(),sx=e.clientX-r.left,sy=e.clientY-r.top;let hit=-1,best=15;points[camera].forEach((p,i)=>{const q=screenPoint(p),d=Math.hypot(q[0]-sx,q[1]-sy);if(d<best){best=d;hit=i}});if(hit>=0){clearTimeout(estimateTimer);++estimateSerial;invalidatePreview();previewButton.disabled=false;setStatus('Adjusting a post. Angles will update after release.')}drag=hit>=0?{type:'point',index:hit}:{type:(e.button===1||e.shiftKey)?'pan':'new',sx,sy,ox:view().x,oy:view().y};if(drag.type==='new'){if(points.reduce((n,p)=>n+Math.floor(p.length/2),0)>=64){setStatus('At most 64 posts are supported. Remove one before adding another.','bad');drag=null;return}const p=sourcePoint(e),[w,h]=S.sizes[camera];if(p[0]>=0&&p[1]>=0&&p[0]<w&&p[1]<h){points[camera].push(p);drag={type:'point',index:points[camera].length-1};draw();scheduleEstimate()}}});
canvas.addEventListener('pointermove',e=>{if(!drag)return;if(drag.type==='point'){const p=sourcePoint(e),[w,h]=S.sizes[camera];points[camera][drag.index]=[Math.max(0,Math.min(w-1,p[0])),Math.max(0,Math.min(h-1,p[1]))];draw()}else if(drag.type==='pan'){const r=canvas.getBoundingClientRect();view().x=drag.ox+(e.clientX-r.left-drag.sx);view().y=drag.oy+(e.clientY-r.top-drag.sy);draw()}});function finishPointer(){if(drag&&drag.type==='point')scheduleEstimate();drag=null}canvas.addEventListener('pointerup',finishPointer);canvas.addEventListener('pointercancel',finishPointer);canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,v=view(),old=v.scale,f=Math.exp(-e.deltaY*.001);v.scale=Math.max(.05,Math.min(20,old*f));v.x=x-(x-v.x)*v.scale/old;v.y=y-(y-v.y)*v.scale/old;draw()},{passive:false});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.tab==='preview'){mode='preview';canvas.style.display='none';preview.style.display='block';document.querySelector('#pointActions').style.visibility='hidden'}else{mode='camera';camera=Number(b.dataset.tab);canvas.style.display='block';preview.style.display='none';document.querySelector('#pointActions').style.visibility='visible';if(!views[camera].scale)fit();draw()}});
document.querySelector('#undo').onclick=()=>{if(busy)return;points[camera].pop();draw();scheduleEstimate()};document.querySelector('#clear').onclick=()=>{if(busy)return;points[camera]=[];draw();scheduleEstimate()};document.querySelector('#fit').onclick=fit;
[pitch,roll].forEach(input=>input.addEventListener('input',()=>{clearTimeout(estimateTimer);++estimateSerial;previewButton.disabled=false;invalidatePreview();setStatus('Angles adjusted. Preview the displayed result before using it.')}));
previewButton.onclick=async()=>{if(previewButton.disabled)return;const selected=rotation();if(!selected.every(Number.isFinite)){setStatus('Enter valid pitch and roll angles.','bad');return}busy=true;stage.classList.add('busy');previewButton.disabled=true;pitch.disabled=true;roll.disabled=true;invalidatePreview();setStatus('Rendering a temporary still preview with NONA…');try{const reply=await post('/api/preview',{rotation:selected}),loaded=await image(reply.preview);if(finishing){URL.revokeObjectURL(loaded.objectUrl);return}if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=loaded.objectUrl;preview.src=previewUrl;preview.onload=()=>{};busy=false;stage.classList.remove('busy');previewButton.disabled=false;pitch.disabled=false;roll.disabled=false;previewRotation=selected;use.disabled=false;document.querySelector('#previewTab').disabled=false;document.querySelector('#previewTab').click();setStatus('Inspect the walls and both ends of the rink. Use angles when satisfied.','ok')}catch(e){busy=false;stage.classList.remove('busy');previewButton.disabled=false;pitch.disabled=false;roll.disabled=false;setStatus(e.message,'bad')}};
async function complete(action){if(finishing||(busy&&action==='use'))return;finishing=true;try{await post('/api/complete',{action,rotation:rotation()});const cancelled=action==='cancel';releaseObjectUrls();document.body.innerHTML=`<main class="page"><section class="panel"><h1>${cancelled?'Calibration cancelled':'Selection complete'}</h1><p>${cancelled?'The stitching calibration is stopping.':'You may close this window. Stitching calibration is continuing.'}</p></section></main>`}catch(e){finishing=false;busy=false;stage.classList.remove('busy');previewButton.disabled=false;pitch.disabled=false;roll.disabled=false;setStatus(e.message,'bad')}}document.querySelector('#skip').onclick=()=>complete('skip');document.querySelector('#cancel').onclick=()=>complete('cancel');use.onclick=()=>complete('use');
try{const draft=JSON.parse(localStorage.getItem(S.draftKey)||'null');if(Array.isArray(draft)&&draft.length===2)for(let c=0;c<2;c++)if(Array.isArray(draft[c]))points[c]=draft[c].slice(0,128).filter(p=>Array.isArray(p)&&p.length===2&&p.every(Number.isFinite))}catch(error){console.warn('Could not restore selector draft',error)}
Promise.allSettled([image('/image/0'),image('/image/1')]).then(results=>{const failed=results.find(result=>result.status==='rejected');if(failed){results.forEach(result=>{if(result.status==='fulfilled')URL.revokeObjectURL(result.value.objectUrl)});throw failed.reason}const loaded=results.map(result=>result.value);loaded.forEach((value,index)=>images[index]=value);fit();scheduleEstimate()}).catch(error=>setStatus(error.message,'bad'));addEventListener('resize',resize);addEventListener('beforeunload',releaseObjectUrls);resize();
</script></body></html>"""
